name: Streamlit CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic Streamlit test
        run: |
          echo "Testing Streamlit app launch"
          # Run Streamlit app in the background and log output
          nohup streamlit run login.py --server.headless true & 
          STREAMLIT_PID=$!
          sleep 10
          # Check if Streamlit is running, and then kill the process
          if ps -p $STREAMLIT_PID > /dev/null; then
            echo "Streamlit app launched successfully"
            kill $STREAMLIT_PID
          else
            echo "Streamlit app failed to launch"
            exit 1
          fi

      - name: ✅ CI Success Message
        run: echo "Streamlit app passed CI test ✅"

