name: Lint with Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint on all Python files
        id: pylint
        run: |
          echo "Looking for Python files..."
          FILES=$(find . -name "*.py")
          if [ -z "$FILES" ]; then
            echo "No Python files found. Skipping pylint."
            exit 0
          fi
          pylint $FILES > pylint_output.txt || true
          cat pylint_output.txt
          SCORE=$(tail -n 2 pylint_output.txt | grep 'Your code has been rated at' | awk '{print $7}' | cut -d'/' -f1)
          echo "Pylint score is $SCORE"
          SCORE_INT=${SCORE%.*}
          if [ "$SCORE_INT" -lt 8 ]; then
            echo "❌ Pylint score too low"
            exit 1
          fi

      - name: ✅ Pylint Passed
        if: success()
        run: echo "Pylint score is acceptable ✅"
